# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://rer98.github.io/jose/"

git_url = "https://github.com/rer98/jose/tree/master/"

def custom_doc_links(name): return None
